export const REGISTER_ARTIST_REQUEST = "REGISTER_ARTIST_REQUEST";
export const REGISTER_ARTIST_SUCCESS = "REGISTER_ARTIST_SUCCESS";
export const REGISTER_ARTIST_FAILURE = "REGISTER_ARTIST_FAILURE";

export const REGISTER_COLLECTOR_REQUEST = "REGISTER_COLLECTOR_REQUEST";
export const REGISTER_COLLECTOR_SUCCESS = "REGISTER_COLLECTOR_SUCCESS";
export const REGISTER_COLLECTOR_FAILURE = "REGISTER_COLLECTOR_FAILURE";

export const LOGIN_ARTIST_REQUEST = "LOGIN_ARTIST_REQUEST";
export const LOGIN_ARTIST_SUCCESS = " LOGIN_ARTIST_SUCCESS";
export const LOGIN_ARTIST_FAILURE = " LOGIN_ARTIST_FAILURE";

export const LOGIN_COLLECTOR_REQUEST = "LOGIN_COLLECTOR_REQUEST";
export const LOGIN_COLLECTOR_SUCCESS = "LOGIN_COLLECTOR_SUCCESS";
export const LOGIN_COLLECTOR_FAILURE = "LOGIN_COLLECTOR_FAILURE";


export const GET_ARTIST_USER_REQUEST = "GET_ARTIST_USER_REQUEST"
export const GET_ARTIST_USER_SUCCESS = "GET_ARTIST_USER_SUCCESS";
export const GET_ARTIST_USER_FAILURE = "GET_ARTIST_USER_FAILURE";

export const GET_COLLECTOR_USER_REQUEST = "GET_COLLECTOR_USER_REQUEST "
export const GET_COLLECTOR_USER_SUCCESS = "GET_COLLECTOR_USER_SUCCESS";
export const GET_COLLECTOR_USER_FAILURE = "GET_COLLECTOR_USER_FAILURE";

export const ADD_TO_FAVORITE_REQUEST = "ADD_TO_FAVORITE_REQUEST"
export const  ADD_TO_FAVORITE_SUCCESS = "ADD_TO_FAVORITE_SUCCESS";
export const  ADD_TO_FAVORITE_FAILURE = "ADD_TO_FAVORITE_FAILURE";


export const LOGOUT = "LOGOUT"
export const LOGOUT_REQUEST = "LOGOUT_REQUEST"


